name: imiPet
main: cn.mcres.imiPet.ImiPet
version: "2.5.0-b04"
authors:
  - inrhor
  - GAYHHY
softdepend:
  - VexView
  - Vault
  - PlaceholderAPI
  - MXBukkitLib
  - HolographicDisplays
  - TrHologram
commands:
  imipet:
    description: imipet command
    usage: /<command>
